version: '3.8'

services:
  # ----------- db ----------- #
  postgres:
    image: postgres:14.10
    container_name: postgres
    restart: always
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRESQL_USER=${POSTGRES_USER}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
      - ALLOW_EMPTY_PASSWORD=${HIDE_EMPTY_PASSWORD}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}

  # ----------- bus ----------- #
  bus:
    image: jrgiadach/soabus:v1
    container_name: soabus
    restart: always
    ports:
      - "5000:5000"

  # ----------- servicios ----------- #
  dbcon-service:
    container_name: dbcon-service
    restart: always
    build:
      context: ./servicios
      dockerfile: Dockerfile
    command: sh -c "sleep 6 && python -u db_connect.py"
    volumes:
      - ./servicios:/app/
    depends_on:
      - postgres
      - bus

  usrlg-service:
    container_name: usrlg-service
    restart: always
    build:
      context: ./servicios
      dockerfile: Dockerfile
    command: sh -c "sleep 6 && python -u user_login.py"
    volumes:
      - ./servicios:/app/
    depends_on:
      - postgres
      - bus

  usrmn-service:
    container_name: usrmn-service
    restart: always
    build:
      context: ./servicios
      dockerfile: Dockerfile
    command: sh -c "sleep 6 && python -u user_management.py"
    volumes:
      - ./servicios:/app/
    depends_on:
      - postgres
      - bus